# Generated by Django 5.1.2 on 2024-10-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id'], 'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتری ها  '},
        ),
    ]
