# Generated by Django 5.1.2 on 2024-10-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='price_paid',
            field=models.BigIntegerField(default=0, verbose_name=' پول  پرداختی    '),
        ),
    ]
