# Generated by Django 5.1.2 on 2024-11-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_payments_price_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='حساب در فروشگاه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='price_mandeh',
            field=models.PositiveBigIntegerField(default=0, verbose_name='باقی مانده در فروشگاه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='price_paid_all',
            field=models.PositiveBigIntegerField(default=0, verbose_name=' پول  پرداختی  ای کل    '),
        ),
        migrations.AlterField(
            model_name='payments',
            name='price_paid',
            field=models.PositiveBigIntegerField(default=0, verbose_name=' پول  پرداختی    '),
        ),
    ]
