# Generated by Django 5.1.2 on 2024-10-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_status_product_is_mojod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
