# Generated by Django 5.0.7 on 2024-11-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mojodi',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
