# Generated by Django 5.1.2 on 2024-11-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_mojodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mojodi',
            field=models.BigIntegerField(default=0),
        ),
    ]
