# Generated by Django 5.1.2 on 2024-11-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_mojodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mojodi',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='percent_sod',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_selling',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sod',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
