# Generated by Django 5.0.7 on 2024-10-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alert_ticket'),
        ('customer', '0004_alter_payments_price_paid'),
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='alert',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='product.product'),
        ),
    ]
