# Generated by Django 5.0.7 on 2024-11-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ticket_awnser_ticket_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
