# Generated by Django 5.1.2 on 2024-10-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
