# Generated by Django 5.1.2 on 2024-11-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_invoicesale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesale',
            name='last_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesale',
            name='off',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='تخفیف  شرکت '),
        ),
        migrations.AlterField(
            model_name='invoicesale',
            name='price_nahayi',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productitemsale',
            name='price_kol',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productitemsale',
            name='price_selling',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت فروش'),
        ),
    ]
