# Generated by Django 5.1.2 on 2024-10-14 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_product_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت خرید')),
                ('tedad', models.PositiveBigIntegerField(default=0, verbose_name='موجودی')),
                ('price_kol', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ افزودن محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ایتم محصول',
                'verbose_name_plural': 'ایتم محصولات برای خرید',
            },
        ),
        migrations.CreateModel(
            name='InvoiceShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=255, verbose_name='شرکت خرید')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ افزودن محصول')),
                ('off', models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف  شرکت ')),
                ('keriyeh', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='تخفیف  شرکت ')),
                ('price_nahayi', models.BigIntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='shopping.productitem')),
            ],
            options={
                'verbose_name': 'خرید  محصول',
                'verbose_name_plural': 'خرید  محصولات  ',
            },
        ),
    ]
