# Generated by Django 5.1.2 on 2024-10-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceshop',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='shopping.productitem'),
        ),
    ]
