# Generated by Django 5.1.2 on 2024-10-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_productitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceshop',
            name='phone_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شرکت '),
        ),
    ]
